#!/usr/bin/env python3
"""Build the HSK 2.0 word list: lang/zh/hsk.js and data/zh/hsk.json.

Two outputs from one source, for the same split English has:

  lang/zh/hsk.js      word -> 'HSK N', read by lang/zh/dictionary.js so a looked
                      up Chinese word gets its level, and by the dashboard's
                      level backfill. Small, and loaded only where the
                      dictionary is (never the content script).
  data/zh/hsk.json    the starter list in the Export format, so Dashboard ->
                      Import takes it: six folders, HSK 1 to HSK 6.

Source: https://github.com/drkameleon/complete-hsk-vocabulary (MIT). Its
`level` array tags each word with every list it is on; `old-N` is HSK 2.0,
which is what lang/zh/index.js `levels` names. A word on more than one old
level keeps the easiest. 4,991 words once duplicates fold.

A starter card carries pinyin in `ipa` and the source's English meanings in
`def`, which VT.glossOf falls back to when there is no Vietnamese gloss. No MT
crawl here (build-korean-list.py's warning is why): `vi` is null, and the side
panel asks for it the first time the word is clicked (lookup.js resolveWord).

Cache is /tmp/vocab-track-hsk; delete it to re-download.
"""

import importlib.util
import json
import pathlib
import re
import time
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location('ielts', HERE.parent / 'build-ielts-list.py')
ielts = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ielts)

REPO = ielts.REPO
OUT_JS = REPO / 'lang' / 'zh' / 'hsk.js'
OUT_JSON = REPO / 'data' / 'zh' / 'hsk.json'
WORK = pathlib.Path('/tmp/vocab-track-hsk')
SRC = WORK / 'complete.json'
SOURCE = ('https://raw.githubusercontent.com/drkameleon/'
          'complete-hsk-vocabulary/main/complete.json')

LEVELS = [f'HSK {n}' for n in range(1, 7)]
# Four colours exist (dashboard.html #dlg-color), so they cycle.
COLORS = ['sage', 'sky', 'ochre', 'clay', 'sage', 'sky']
HAN = re.compile(r'^[㐀-鿿\U00020000-\U0002ebef]+$')


def fetch():
    if not SRC.exists():
        WORK.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(SOURCE, timeout=60) as res:
            SRC.write_bytes(res.read())
    return json.loads(SRC.read_text(encoding='utf-8'))


def old_level(tags):
    """The easiest HSK 2.0 level in a word's tag list, as 1-6, or None."""
    nums = [int(t[4:]) for t in tags if re.fullmatch(r'old-[1-6]', t)]
    return min(nums) if nums else None


def pick(rows):
    """[(word, level, pinyin, meanings)] in level then source order, one per word."""
    seen = {}
    for row in rows:
        word = row.get('simplified', '')
        level = old_level(row.get('level', []))
        if not level or not HAN.match(word):
            continue
        form = (row.get('forms') or [{}])[0]
        pinyin = form.get('transcriptions', {}).get('pinyin') or None
        meanings = '; '.join(form.get('meanings') or []) or None
        if word not in seen or level < seen[word][1]:
            seen[word] = (word, level, pinyin, meanings)
    return sorted(seen.values(), key=lambda e: e[1])


def write_js(items):
    table = json.dumps({w: f'HSK {lvl}' for w, lvl, _, _ in items},
                       ensure_ascii=False, separators=(',', ':'))
    OUT_JS.write_text(f'''// GENERATED by tools/zh/build-hsk-list.py — do not edit by hand.
//
// A Simplified Chinese word -> its HSK 2.0 level, from
// drkameleon/complete-hsk-vocabulary (MIT). See README, "Word lists".
//
// Loaded in the side panel, the dashboard and the test page only — never the
// content script, so no page carries these {len(items)} words.
const ZH_HSK = {table};

// The HSK level of a word, or null. Exact match only: Chinese does not inflect,
// so there is no stem to fall back to.
function hskLevel(word) {{
  return ZH_HSK[String(word ?? '').trim()] ?? null;
}}
''', encoding='utf-8')


def write_json(items):
    day = 24 * 60 * 60 * 1000
    now = int(time.time() * 1000)
    folders = {}
    for n, name in enumerate(LEVELS, 1):
        fid = f'zh-hsk{n}'
        folders[fid] = {'id': fid, 'name': name, 'color': COLORS[n - 1], 'icon': '\U0001F4D5',
                        'lang': 'zh', 'auto': False, 'added': now,
                        'desc': f'HSK 2.0 level {n}.'}
    words = {}
    for i, (word, level, pinyin, meanings) in enumerate(items):
        # Kept in step with VT.newEntry by hand, as build-korean-list.py does.
        words[word] = {
            'word': word, 'lang': 'zh', 'folders': [f'zh-hsk{level}'],
            'level': f'HSK {level}', 'pos': None, 'gram': None, 'vi': None,
            'context': None, 'ipa': pinyin, 'def': meanings,
            'audio': None, 'ipaUs': None, 'audioUs': None,
            'senses': [], 'synonyms': [], 'related': [],
            'sources': [SOURCE],
            'added': now, 'ease': 2.5, 'interval': 0, 'reps': 0,
            # The drip-feed every starter list uses: a course, not a wall.
            'due': now + (i // ielts.NEW_PER_DAY) * day,
        }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    payload = {'exported': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
               'folders': folders, 'words': words}
    OUT_JSON.write_text(json.dumps(payload, ensure_ascii=False, indent=1), encoding='utf-8')


def selftest():
    assert old_level(['newest-1', 'new-1', 'old-1']) == 1
    assert old_level(['new-7']) is None
    assert old_level(['old-5', 'old-3']) == 3
    got = pick([
        {'simplified': '学生', 'level': ['old-2'], 'forms': []},
        {'simplified': '学生', 'level': ['old-1'],
         'forms': [{'transcriptions': {'pinyin': 'xué sheng'}, 'meanings': ['student']}]},
        {'simplified': 'abc', 'level': ['old-1']},
        {'simplified': '阿拉伯语', 'level': ['new-7']},
    ])
    assert got == [('学生', 1, 'xué sheng', 'student')], got


def main():
    selftest()
    items = pick(fetch())
    write_js(items)
    write_json(items)
    counts = '  '.join(f'HSK {n} {sum(1 for e in items if e[1] == n)}' for n in range(1, 7))
    print(f'{OUT_JS.relative_to(REPO)}: {OUT_JS.stat().st_size // 1024}KB')
    print(f'{OUT_JSON.relative_to(REPO)}: {len(items)} words, {OUT_JSON.stat().st_size // 1024}KB')
    print(f'  {counts}')
    print(f'  last card due in {(len(items) - 1) // ielts.NEW_PER_DAY} days')


if __name__ == '__main__':
    main()
