#!/usr/bin/env python3
# Builds lang/en/cefr.js: an English word -> easiest CEFR level map, from the
# Open Language Profiles vocabulary profiles. No lookup API carries a CEFR level
# (Cambridge did, before its bot wall), so the English pack sets a word's level
# from this bundled list instead.
#
# Sources (see README, "Word lists"):
#   - CEFR-J Vocabulary Profile 1.5 — A1-B2. Copyright Tono Laboratory, Tokyo
#     University of Foreign Studies. Free for research and commercial use with
#     citation.
#   - Octanove Vocabulary Profile C1/C2 1.0 — C1-C2. CC BY-SA 4.0.
# Both via https://github.com/openlanguageprofiles/olp-en-cefrj
#
# A word can appear under several parts of speech and levels; the stored level
# is the EASIEST one, the way a word is "known" once any sense of it is.
import csv
import io
import json
import re
import subprocess

BASE = "https://raw.githubusercontent.com/openlanguageprofiles/olp-en-cefrj/master"
SOURCES = [
    f"{BASE}/cefrj-vocabulary-profile-1.5.csv",
    f"{BASE}/octanove-vocabulary-profile-c1c2-1.0.csv",
]
ORDER = ["A1", "A2", "B1", "B2", "C1", "C2"]
RANK = {level: i for i, level in enumerate(ORDER)}
# The same shape the English pack accepts as a word: letters and inner hyphens,
# so phrases, abbreviations and anything with a digit or a dot fall out.
WORD = re.compile(r"^[a-z]+(-[a-z]+)*$")

# curl, not urllib: a stock macOS python has no CA bundle and fails TLS, while
# curl uses the system trust store. -fsSL fails loudly on an HTTP error.
def fetch(url):
    return subprocess.run(
        ["curl", "-fsSL", url], check=True, capture_output=True, text=True
    ).stdout


levels = {}
for url in SOURCES:
    text = fetch(url)
    for row in csv.DictReader(io.StringIO(text)):
        cefr = (row.get("CEFR") or "").strip().upper()
        if cefr not in RANK:
            continue
        # A headword can list spelling variants separated by "/".
        for variant in (row.get("headword") or "").split("/"):
            word = variant.strip().lower()
            if not WORD.match(word):
                continue
            if word not in levels or RANK[cefr] < RANK[levels[word]]:
                levels[word] = cefr

out = dict(sorted(levels.items()))
body = json.dumps(out, ensure_ascii=False, separators=(",", ":"))
js = f"""// GENERATED by tools/build-cefr-list.py — do not edit by hand.
//
// An English word -> its easiest CEFR level, from the Open Language Profiles
// CEFR-J Vocabulary Profile 1.5 (Tono Lab, TUFS; free with citation) and the
// Octanove Vocabulary Profile C1/C2 1.0 (CC BY-SA 4.0). See README, "Word lists".
//
// No lookup API carries a CEFR level, so the English pack reads a word's level
// from here. Loaded in the side panel, the dashboard and the test page only —
// NEVER the content script, so no page is made to carry these {len(out)} words.
const EN_CEFR = {body};

// The easiest CEFR level recorded for a word, or null. Pure.
//
// The list holds headwords, not every inflected form, so an exact miss falls
// back to a few de-inflected candidates: a reader's "deteriorating" should still
// find "deteriorate", "studies" should find "study". English-only and
// deliberately shallow — a miss just leaves the level null, which is the state
// before this list existed, so a wrong guess is the only thing to avoid.
function cefrLevel(word) {{
  const w = String(word ?? '').trim().toLowerCase();
  if (!w) return null;
  if (EN_CEFR[w]) return EN_CEFR[w];
  const bases = [];
  if (w.endsWith('ies')) bases.push(w.slice(0, -3) + 'y');
  if (w.endsWith('ing')) bases.push(w.slice(0, -3), w.slice(0, -3) + 'e');
  if (w.endsWith('ed')) bases.push(w.slice(0, -2), w.slice(0, -1));
  if (w.endsWith('es')) bases.push(w.slice(0, -2));
  if (w.endsWith('s')) bases.push(w.slice(0, -1));
  if (w.endsWith('ly')) bases.push(w.slice(0, -2));
  for (const base of bases) {{
    if (EN_CEFR[base]) return EN_CEFR[base];
  }}
  return null;
}}
"""
with open("lang/en/cefr.js", "w", encoding="utf-8") as f:
    f.write(js)
print(f"wrote lang/en/cefr.js with {len(out)} words")
